### ISSUE TITLE
Ukrainian language

### ISSUE THREAD

**Issue by MetenBouldry** [Atria1234/WideChests#13]
Please add Ukrainian to the mod. The translation is below. Can the translation be updated on this resource or on some other?

[item-group-name]
WideChests_merged-chests=Об'єднані скрині

[chest-name]
WideChests_wide-wooden-chest=Дерев'яна скриня __1__ шириною
WideChests_high-wooden-chest=Дерев'яна скриня заввишки __1__
WideChests_wooden-chest-warehouse=Дерев'яний склад __1__ x __2__
WideChests_wooden-chest-trashdump=Дерев'яний смітник __1__ x __2__

WideChests_wide-iron-chest=Залізна скриня шириною __1__
WideChests_high-iron-chest=Залізна скриня заввишки __1__
WideChests_iron-chest-warehouse=Залізний склад __1__ x __2__
WideChests_iron-chest-trashdump=Залізний смітник __1__ x __2__

WideChests_wide-steel-chest=Сталева скриня шириною __1__
WideChests_high-steel-chest=Сталева скриня заввишки __1__ 
WideChests_steel-chest-warehouse=Стальний склад __1__ x __2__
WideChests_steel-chest-trashdump=Сталевий смітник __1__ x __2__

[item-name]
WideChests_merge-chest-selector=Інструмент об'єднання скринь

[shortcut-name]
WideChests_merge-chest-selector=Об'єднання скринь

[controls]
WideChests_rotate-blueprint-clockwise=Поверніть креслення за годинниковою стрілкою
WideChests_rotate-blueprint-couterclockwise=Поверніть креслення проти годинникової стрілки

[controls-description]
WideChests_rotate-blueprint-clockwise=Працює над кресленнями з об'єднаними скринями.
WideChests_rotate-blueprint-couterclockwise=Працює над кресленнями з об'єднаними скринями.

[mod-setting-name]
WideChests_mergeable-chest-wooden-chest=Режим злиття дерев'яних скринь
WideChests_mergeable-chest-iron-chest=Режим злиття залізних скринь
WideChests_mergeable-chest-steel-chest=Режим злиття стальних скринь
WideChests_max-chest-width=Максимальна ширина скринь
WideChests_max-chest-height=Максимальна висота скринь
WideChests_max-chest-area=Максимальна площа скринь
WideChests_inventory-size-multiplier=Мультиплікатор розміру інвертарю
WideChests_inventory-size-limit=Обмеження розміру інвертарю 
WideChests_sprite-decal-chance=Зміна для спрайт-наклейки
WideChests_warehouse-threshold=Поріг розміру складу
WideChests_whitelist-chest-sizes=Білий список об'єднаних скринь
WideChests_mirror-whitelists=Налаштування дзеркального білого списку
WideChests_circuit-connector-position=Положення підключення ланцюга
WideChests_allow-delete-items=Дозволити недійсні елементи

[mod-setting-description]
WideChests_max-chest-width=Максимальна ширина об'єднаних скринь. Встановіть мод WideChestsUnlimited, якщо хочете, щоб обмеження було більше 42.
WideChests_max-chest-height=Максимальна висота об'єднаних скринь. Встановіть мод WideChestsUnlimited, якщо хочете, щоб ліміт був вищим за 42.
WideChests_max-chest-area=Максимальна площа об'єднаних скринь. Встановіть мод WideChestsUnlimited, якщо хочете, щоб ліміт був більшим за 1600.
WideChests_inventory-size-multiplier=Розмір інвентарю об'єднаної скрині - це сума розмірів інвентарю окремих об'єднаних скринь. Це число множиться на цей параметр.
WideChests_inventory-size-limit=Максимальний розмір інвентарю, який може мати об'єднана скриня. Зазвичай розмір інвентарю об'єднаної скрині дорівнює сумі розмірів інвентарю окремих об'єднаних скринь (а потім помноженій на вищевказаний множник).
WideChests_sprite-decal-chance=Відсоткова ймовірність того, що на об'єднаних скринях з'являться наклейки (графічний варіант). Поки що лише склади (об'єднані скрині з обома сторонами більшими від 1 до "Порогу розміру складу") мають наклейки.
WideChests_warehouse-threshold=Смітник буде використано при об'єднанні області, більшої за X з обох боків.
WideChests_whitelist-chest-sizes=Вказує, які скрині ввімкнено. Це список значень типу "AxB", розділених пробілом, "A" і "B" можуть бути цілими числами (більшими за 0) або "N", які представляють собою символ підстановки (це означає, що він буде відповідати всьому). Наприклад, "1x6 2x4 13xN" дозволить об'єднати лише скрині 1x6, 2x4, 13x1, 13x2, 13x3, 13x4 і т.д... За замовчуванням "NxN" дозволяє об'єднувати все, що завгодно (тобто до 42x42 за замовчуванням).
WideChests_mirror-whitelists=Якщо увімкнено, вам не потрібно вказувати і "AxB", і "BxA". Будь-який з них буде працювати як обидва.
WideChests_circuit-connector-position=Вказує, де буде розміщено з'єднувач ланцюга на об'єднаних скринях.
WideChests_allow-delete-items=Дозволяє видаляти предмети під час об'єднання або розділення скринь.

[string-mod-setting]
WideChests_mergeable-chest-wooden-chest-none=Ні
WideChests_mergeable-chest-wooden-chest-chest=Тільки скрині
WideChests_mergeable-chest-wooden-chest-warehouse=Тільки склад
WideChests_mergeable-chest-wooden-chest-trashdump=Тільки смітник
WideChests_mergeable-chest-wooden-chest-chest-warehouse=Скриня та склад
WideChests_mergeable-chest-wooden-chest-chest-trashdump=Скриня і смітник
WideChests_mergeable-chest-wooden-chest-warehouse-trashdump=Склад і звалище
WideChests_mergeable-chest-wooden-chest-chest-warehouse-trashdump=Усе

WideChests_mergeable-chest-iron-chest-none=Ні
WideChests_mergeable-chest-iron-chest-chest=Тільки скрині
WideChests_mergeable-chest-iron-chest-warehouse=Тільки склад
WideChests_mergeable-chest-iron-chest-trashdump=Тільки смітник
WideChests_mergeable-chest-iron-chest-chest-warehouse=Скриня та склад
WideChests_mergeable-chest-iron-chest-chest-trashdump=Скриня і смітник
WideChests_mergeable-chest-iron-chest-warehouse-trashdump=Склад і звалище
WideChests_mergeable-chest-iron-chest-chest-warehouse-trashdump=Усе

WideChests_mergeable-chest-steel-chest-none=Ні
WideChests_mergeable-chest-steel-chest-chest=Тільки скрині
WideChests_mergeable-chest-steel-chest-warehouse=Тільки склад
WideChests_mergeable-chest-steel-chest-trashdump=Тільки смітник
WideChests_mergeable-chest-steel-chest-chest-warehouse=Скриня та склад
WideChests_mergeable-chest-steel-chest-chest-trashdump=Скриня і смітник
WideChests_mergeable-chest-steel-chest-warehouse-trashdump=Склад і звалище
WideChests_mergeable-chest-steel-chest-chest-warehouse-trashdump=Усе

WideChests_circuit-connector-position-center-center=Найближче до центру
WideChests_circuit-connector-position-right-top=Праворуч вгорі
WideChests_circuit-connector-position-right-middle=Праворуч посередині
WideChests_circuit-connector-position-right-bottom=Праворуч внизу
WideChests_circuit-connector-position-left-top=Зліва вгорі
WideChests_circuit-connector-position-left-middle=Ліворуч посередині
WideChests_circuit-connector-position-left-bottom=Зліва внизу
WideChests_circuit-connector-position-bottom-right=Внизу праворуч
WideChests_circuit-connector-position-bottom-middle=Внизу посередині
WideChests_circuit-connector-position-bottom-left=Внизу зліва

[flying-text]
WideChests_items-would-be-deleted-merge=Злиття призведе до видалення елемента
WideChests_items-would-be-deleted-split=Розділення призведе до видалення елемента

**Comment by Atria1234** [comment]
Damn if only you sent this couple of hours ago I could have added it to 5.0.2 update. I'll add it to 5.0.3, but don't know when it will come out.

**Comment by MetenBouldry** [comment]
Thank you.  It's okay, I'll wait.

**Comment by Atria1234** [comment]
Included in 5.0.3
