### ISSUE TITLE
Issue with Latest version of Merging Chests and Space Exploration

### ISSUE THREAD

**Issue by StephJ2Fan** [Atria1234/WideChests#15]
The mod Space Exploration (0.6.137) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event space-exploration::on_init()
The mod Merging Chests (5.2.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event WideChests::on_force_created (ID 29)
Invalid surface name or index.
stack traceback:
	[C]: in function 'chart'
	...ts__/scripts/event_handlers/on_configuration_changed.lua:22: in function <...ts__/scripts/event_handlers/on_configuration_changed.lua:21>
stack traceback:
	[C]: in function 'create_force'
	__space-exploration__/scripts/system-forces.lua:26: in function 'setup_system_forces'
	__space-exploration__/control.lua:2001: in function 'callback'
	__space-exploration__/scripts/event.lua:20: in function 'sequence'
	__space-exploration__/scripts/event.lua:59: in function 'trigger'
	__space-exploration__/scripts/event.lua:63: in function <__space-exploration__/scripts/event.lua:63>

I have also reported this to Space Exploration

**Comment by Atria1234** [comment]
Not SE's problem, will be fixed soon in 5.2.1

**Comment by Atria1234** [comment]
5.2.1 released
