### ISSUE TITLE
Description settings are unclear

### ISSUE THREAD

**Issue by Stargateur** [Atria1234/WideChests#7]
> mergable-chest-name=Chest type that can be merged. Install WideChestsAllTypes mod to enable all at once.

Make sense clear

> max-chest-width=Maximum width of merged chest. Install WideChestsUnlimited mod if you want limit to be higher than 42.

Make sense clear

> max-chest-height=Maximum height of merged chest. Install WideChestsUnlimited mod if you want limit to be higher than 42.

Make sense clear

> max-chest-area=Maximum area of merged chest. Install WideChestsUnlimited mod if you want limit to be higher than 1600.

This should include that it's override the stack size of chests, BTW would be nice to avoid this. Also precise merging chest can only make rectangle.

> inventory-size-multiplier=Changing this may result in loss of items when merging or splitting!

multiply what with what ?

> inventory-size-limit=Changing this may result in loss of items when merging or splitting!

size limit of what ? number of slot in chest ?

> sprite-decal-chance=Percent chance of decal for sprite decal.

????????????????

> warehouse-threshold=Trashdump will be used when merging area of width and height larger than X.

What is Trashdump ? width * height  > X ?

> whitelist-chest-sizes=List of AxB values (separated by space) where A and B are any number or capital letter N (representing a wildcard).

Totally unclear.

**Comment by Atria1234** [comment]
> This should include that it's override the stack size of chests, BTW would be nice to avoid this. Also precise merging chest can only make rectangle.

Only way to avoid this would be to have separate checkbox for it, which should warn that bots might not be able to place chests bigger than stack size.

> multiply what with what ?

I though it was self explanatory. I'll give better explanation to description.

> size limit of what ? number of slot in chest ?

Yes, also to be updated

> ????????????????

It is a graphical option, will update

> What is Trashdump ? width * height > X ?

Have you tried to merge chests larger than 6x6 before (as long as you didn't modify this setting)

> Totally unclear.

I agree it is not very clear. Could you try to explain in short description how would you explain following

- it is a list of values, separated by space
- each value should be two subvalues separated by any of these characters "×xX"
- each subvalue should either be a number or character "N" (which means any number)

The list specified which chests are enabled, so if you for example set it to
- "Nx1 1xN" will only allow chests 1 high and 1 wide
- "1x6 6x1" will only allow 1x6 and 6x1 chests to be merged

**Comment by Stargateur** [comment]
> Only way to avoid this would be to have separate checkbox for it, which should warn that bots might not be able to place chests bigger than stack size.

Sorry I bring this up, mixing issues, but yeah I think this could be nice to have a separate option for that. Having chest stack to 1000 is a side effect that should probably be opt-in.

> Have you tried to merge chests larger than 6x6 before (as long as you didn't modify this setting)

I did, Oh so that how you call the graphic for very big area, I see. So this mean that if A and B are greater than X in AxB, the graphic will choice the trashdump sprite. Ok so I would write:

warehouse-threshold=Trashdump sprite will be used for AxB chest when A and B are both larger than X.

> Could you try to explain in short description

Well you did it in your comment :p

> each value should be two subvalues separated by any of these characters "×xX"

pick one, let's say `x`.

Using your comment:

whitelist-chest-sizes=Specified which chests are enabled. It's a list area values like 'AxB' separated by space, 'A' and 'B' can either be a integer (greater than 0) or 'N' that represent a wildcard (meaning it will match everything). For example, "1x6 2x4 13xN" will only allow 1x6, 2x4, 13x1, 13x2, 13x3, 13x4, etc... chests to be merged. Default 'NxN' allow anything (so up to 42x42 by default).

There is no problem with long description IMO, since the description is hidden unless you put your cursor on the '?'. No need to restrict information.

**Comment by Atria1234** [comment]
I'm not big fan of descriptions on multiple lines. But having short unhelpful description is also pretty bad. 😄 I'll play with it and see how it looks in the game

**Comment by Atria1234** [comment]
Published new version of library, hopefully it is clearer now
